Repository lasp/basilisk, pull requests merged in 2023-09, with the labels that each got.

#134 Feature/31 continuous cm estimation
  docs/source/Support/bskReleaseNotes.rst
  src/CMakeLists.txt
  src/architecture/msgPayloadDefC/CMEstDataMsgPayload.h
  src/fswAlgorithms/stateEstimation/thrustCMEstimation/_UnitTest/test_thrustCMEstimation.py
  src/fswAlgorithms/stateEstimation/thrustCMEstimation/thrustCMEstimation.cpp
  src/fswAlgorithms/stateEstimation/thrustCMEstimation/thrustCMEstimation.h
  src/fswAlgorithms/stateEstimation/thrustCMEstimation/thrustCMEstimation.i
  src/fswAlgorithms/stateEstimation/thrustCMEstimation/thrustCMEstimation.rst
Labels: enhancement

#138 Analyses/120 momentum management analysis
  examples/BskSim/BSK_SEPMasters.py
  examples/BskSim/models/BSK_EnvironmentEarth.py
  examples/BskSim/models/BSK_SEPDynamics.py
  examples/BskSim/models/BSK_SEPFsw.py
  examples/BskSim/plotting/BSK_SEPPlotting.py
  examples/BskSim/scenarios/scenario_SEPPoint.py
Labels: enhancement

#130 Feature/360 update dv execution module
  src/fswAlgorithms/dvGuidance/dvExecuteGuidance/_UnitTest/test_dvExecuteGuidance.py
  src/fswAlgorithms/dvGuidance/dvExecuteGuidance/dvExecuteGuidance.c
  src/fswAlgorithms/dvGuidance/dvExecuteGuidance/dvExecuteGuidance.h
  src/fswAlgorithms/dvGuidance/dvExecuteGuidance/dvExecuteGuidance.rst
Labels: enhancement

#105 Refactor/104 flyby point singularity fix
  src/fswAlgorithms/attGuidance/flybyPoint/flybyPoint.cpp
  src/fswAlgorithms/attGuidance/flybyPoint/flybyPoint.h
Labels: bug, refactor

#116 Feature/281 triangulation covariance
  src/architecture/msgPayloadDefC/CameraLocalizationMsgPayload.h
  src/fswAlgorithms/pointCloudProcessing/cameraTriangulation/_UnitTest/test_cameraTriangulation.py
  src/fswAlgorithms/pointCloudProcessing/cameraTriangulation/cameraTriangulation.cpp
  src/fswAlgorithms/pointCloudProcessing/cameraTriangulation/cameraTriangulation.h
  src/fswAlgorithms/pointCloudProcessing/cameraTriangulation/cameraTriangulation.rst
Labels: enhancement

#122 Feature/270 full dv guidance scenario
  docs/source/Support/bskReleaseNotes.rst
  examples/BskSim/models/BSK_Fsw.py
  examples/BskSim/plotting/BSK_Plotting.py
  examples/BskSim/scenarios/scenario_LambertGuidance.py
  examples/_default.rst
  src/fswAlgorithms/orbitControl/lambertPlanner/lambertPlanner.cpp
  src/fswAlgorithms/orbitControl/lambertValidator/lambertValidator.cpp
  src/tests/test_bskTestScript.py
Labels: enhancement

#123 Feature/300 closed loop dv scenario
  docs/source/Support/bskReleaseNotes.rst
  examples/BskSim/models/BSK_Dynamics.py
  examples/BskSim/models/BSK_Fsw.py
  examples/BskSim/plotting/BSK_Plotting.py
  examples/BskSim/scenarios/scenario_ClosedLoopManeuver.py
  examples/_default.rst
  src/tests/test_bskTestScript.py
Labels: enhancement

#117 Feature/106 sep point
  docs/source/Support/bskReleaseNotes.rst
  src/CMakeLists.txt
  src/fswAlgorithms/attGuidance/_GeneralModuleFiles/attitudePointingLibrary.cpp
  src/fswAlgorithms/attGuidance/_GeneralModuleFiles/attitudePointingLibrary.h
  src/fswAlgorithms/attGuidance/sepPoint/_UnitTest/test_sepPoint0.py
  src/fswAlgorithms/attGuidance/sepPoint/_UnitTest/test_sepPoint1.py
  src/fswAlgorithms/attGuidance/sepPoint/sepPoint.cpp
  src/fswAlgorithms/attGuidance/sepPoint/sepPoint.h
  src/fswAlgorithms/attGuidance/sepPoint/sepPoint.i
  src/fswAlgorithms/attGuidance/sepPoint/sepPoint.rst
Labels: enhancement, refactor
