Repository lasp/basilisk, pull requests merged in 2023-10, with the labels that each got.

#146 Feature/stepper motor
  src/architecture/msgPayloadDefC/MotorStepCommandMsgPayload.h
  src/fswAlgorithms/effectorInterfaces/stepperMotorController/_UnitTest/test_stepperMotorController.py
  src/fswAlgorithms/effectorInterfaces/stepperMotorController/_UnitTest/test_stepperMotorControllerInterrupt.py
  src/fswAlgorithms/effectorInterfaces/stepperMotorController/stepperMotorController.c
  src/fswAlgorithms/effectorInterfaces/stepperMotorController/stepperMotorController.h
  src/fswAlgorithms/effectorInterfaces/stepperMotorController/stepperMotorController.i
Labels: enhancement

#151 Add capability to thrForceMapping for 3-axis attitude control with DV thrusters
  src/fswAlgorithms/effectorInterfaces/thrForceMapping/thrForceMapping.c
Labels: enhancement

#143 Refactor/142 thruster platform reference integral feedback
  docs/source/Support/bskReleaseNotes.rst
  src/fswAlgorithms/effectorInterfaces/thrusterPlatformReference/_UnitTest/test_thrusterPlatformReference.py
  src/fswAlgorithms/effectorInterfaces/thrusterPlatformReference/thrusterPlatformReference.c
  src/fswAlgorithms/effectorInterfaces/thrusterPlatformReference/thrusterPlatformReference.h
  src/fswAlgorithms/effectorInterfaces/thrusterPlatformReference/thrusterPlatformReference.rst
Labels: enhancement, refactor

#147 Stepper motor/stepper motor profiler
  src/architecture/msgPayloadDefC/StepperMotorMsgPayload.h
  src/fswAlgorithms/effectorInterfaces/stepperMotorProfiler/_UnitTest/test_stepperMotorProfiler.py
  src/fswAlgorithms/effectorInterfaces/stepperMotorProfiler/_UnitTest/test_stepperMotorProfilerInterrupt.py
  src/fswAlgorithms/effectorInterfaces/stepperMotorProfiler/stepperMotorProfiler.c
  src/fswAlgorithms/effectorInterfaces/stepperMotorProfiler/stepperMotorProfiler.h
  src/fswAlgorithms/effectorInterfaces/stepperMotorProfiler/stepperMotorProfiler.i
Labels: enhancement

#145 Analyses/120 momentum management analysis
  examples/BskSim/models/BSK_SEPDynamics.py
  examples/BskSim/models/BSK_SEPFsw.py
  examples/BskSim/scenarios/scenario_SEPPoint.py
Labels: refactor

#157 dvExecuteGuidance module burn time fix
  src/fswAlgorithms/dvGuidance/dvExecuteGuidance/_UnitTest/test_dvExecuteGuidance.py
  src/fswAlgorithms/dvGuidance/dvExecuteGuidance/dvExecuteGuidance.c
  src/fswAlgorithms/dvGuidance/dvExecuteGuidance/dvExecuteGuidance.h
  src/fswAlgorithms/dvGuidance/dvExecuteGuidance/dvExecuteGuidance.rst
Labels: bug

#159 Refactor/stepper motor controller fix
  src/fswAlgorithms/effectorInterfaces/stepperMotorController/_UnitTest/test_stepperMotorController.py
  src/fswAlgorithms/effectorInterfaces/stepperMotorController/stepperMotorController.c
Labels: refactor

#141 Feature/momentum dumping zero net force
  docs/source/Support/bskReleaseNotes.rst
  examples/_default.rst
  examples/scenarioMomentumDumpingZeroNetForce.py
  src/tests/test_scenarioTest.py
Labels: enhancement

#160 Initialize all variables spinningbody
  src/simulation/dynamics/spinningBodies/spinningBodiesTwoDOF/spinningBodyTwoDOFStateEffector.cpp
  src/simulation/dynamics/spinningBodies/spinningBodiesTwoDOF/spinningBodyTwoDOFStateEffector.h
Labels: bug

#162 Refactor/161 one axis solar array point singularity patch
  src/fswAlgorithms/attGuidance/oneAxisSolarArrayPoint/oneAxisSolarArrayPoint.c
  src/fswAlgorithms/attGuidance/oneAxisSolarArrayPoint/oneAxisSolarArrayPoint.h
  src/fswAlgorithms/attGuidance/oneAxisSolarArrayPoint/oneAxisSolarArrayPoint.rst
Labels: bug, refactor

#165 Hot fix/datashader utilities
  src/utilities/datashader_utilities.py
Labels: bug

#167 Feature/accumulated dv inertial frame
  src/architecture/msgPayloadDefC/SCStatesMsgPayload.h
  src/simulation/dynamics/spacecraft/_UnitTest/test_spacecraft.py
  src/simulation/dynamics/spacecraft/spacecraft.cpp
  src/simulation/dynamics/spacecraft/spacecraft.h
Labels: enhancement
